Makefile
pyproject.toml

This PR adds poetry option to install prod vs dev using --only main and make default install with this option Closed #206

Create a division of install packages with poetry dev vs prod

---

apps/billing/mocks.py
apps/billing/services/receipt_host_service.py
apps/billing/tests/test_receipt_host_service.py
apps/billing/tests/test_transaction_service.py
apps/billing/views.py
apps/util/exceptions.py

This PR includes the ilink exception handling, resolve #212.

Catch exception state on ilink web service #212

---

README.md

Specially after the first deployment of this application, it was need to apply a revision of the readme file, to clarify some sections.

docs: a general revision of readme

---

Makefile
docker/Dockerfile

The #232 was merged before my comments have been implemented.
This fixes the #232.

fix: package division main and dev/test

---

apps/shared_revenue/management/commands/export_split_revenue.py
apps/shared_revenue/services/split_export.py
nau_financial_manager/settings.py

This PR includes the condition to not generate empty files when it is exporting the split revenue, resolve #219.

No empty files on Django command that exports split for all organizations #219

---

docker/files/etc/nginx/conf.d/default.conf

When local developing if the application restart, the nginx wasn't autodiscovering the new instance of the app container. With a small line of nginx configuration the nginx uses the internal docker DNS with a short amout of valid time.

fix: nginx auto discovers a new app instance

---

Makefile
apps/billing/services/financial_processor_service.py
apps/billing/services/processor_service.py
apps/billing/services/transaction_service.py
apps/billing/tests/test_transaction_processor_interface.py
apps/billing/tests/test_transaction_service.py

feat: add log xml in and out
On transaction service logs the in and out xml to SageX3.
fixes fccn/nau-financial-manager#271
fix: if error to SageX3 save to error_messages
The error was being saved to output_xml.
The SageX3 output is saved to output_xml field.
The processing error is being saved to error_messages field.
test: input_xml in case of error
Test ensures that in case of error sending to processor we still have the input_xml value.
build: use pytest instead of django test
pytest has better output
test: if retries counter increases
fix: status not updating on success integration to Sage
refactor: split test
fix: save Transaction output_xml
The output_xml wasn't being saved.
Save input data xml before trying to sending and possibly crashing.
refactor: add memoization input xml to …

Multiple changes

---

nau_financial_manager/settings.py

Add `HTTP_CLIENT_DEBUG` and `LOGGING_DEFAULT_ROOT_LEVEL` settings to easily increase verbosity logging of requests module. This will print the http headers and post body.
related to #274

feat: add settings to easily verbose requests to log

---

apps/billing/services/processor_service.py
apps/billing/tests/test_sagex3_processor_service.py

The SOAPAction HTTP header require some value.
If empty string means that the intent of the SOAP
message is provided by the HTTP Request-URI.
relates to #273 and #276

fix: SOAPAction HTTP header should be empty

---

apps/billing/services/processor_service.py
apps/billing/tests/test_sagex3_processor_data.py

The field INVDAT for the Sage X3 should use the date format: YYYYMMDD instead of YYYY-MM-DD.
fixes #295

fix: date issue for X3

---

apps/billing/services/receipt_host_service.py
apps/billing/tests/test_receipt_host_service.py

Add the fixed `document_type` parameter with value of `issued`
when querying iLink, so we can search documents issued by
fixes #299
----
test: receipt host service
Replace `ReceiptDocumentHostForTest` with a override settings configuration.
Improve success test with asserts on iLink GET.

feat: add document_type on iLink integration

---

apps/billing/mocks.py
apps/billing/services/receipt_host_service.py
apps/billing/tests/test_receipt_host_service.py
apps/billing/views.py

fix: ilink get document client

---

apps/billing/tests/test_receipt_host_service.py
apps/billing/views.py

Remove the intermediate `response` on receipt document return.
fccn/nau-technical#25

feat: simplify get document output

---

apps/billing/tests/test_receipt_host_service.py
apps/billing/views.py

- revert: simplify get document output
Rest framework requires json output, if not the output will have the character `"`.
- refactor: use rest vars
- docs: add better doc on get receipt link

Revert simplify get document output

---

apps/billing/services/processor_service.py
apps/billing/tests/test_sagex3_processor_service.py

Fix missing charset on Content Type HTTP header when integrating to Sage X3.
fix #309

fix(x3): content type missing charset

---

apps/billing/services/processor_service.py
apps/billing/tests/test_sagex3_processor_data.py

The country name on field `YCRYNAM` on the XML sent to SageX3 was using the country alpha2 code instead of sending the name in portuguese.
fixes: #312

fix(x3): country name `YCRYNAM` field

---

apps/billing/serializers.py
apps/billing/views.py
nau_financial_manager/settings.py

Added a new `VAT_TAX_RATE` setting.
The excluding vat tax fields were removed from API, but they are calculated dynamic using the `VAT_TAX_RATE` setting.
related to fccn/nau-technical#215

feat: removed prices without vat tax from API

---

apps/billing/serializers.py
apps/billing/tests/test_process_transaction.py

This PR makes a refactor to not send to `SageX3` transactions that have 0 as total amount. That is, the transaction needs to be saved, but not generated from a receipt, as nothing was sold.

Do not send basket with seat with full discount to Sage X3

---

apps/billing/mocks.py
apps/billing/services/receipt_host_service.py
apps/billing/tests/test_receipt_host_service.py

This PR includes validation to `iLink` get issued document.
- Added validation to invalid document_id
- Added validation with success response without a pdf document
Related to #320 and #323.

iLink document validation 

---

apps/billing/management/commands/retry_sage_transactions.py
apps/billing/services/transaction_service.py
apps/billing/tests/test_command_retry_sage_transactions.py
apps/billing/tests/test_transaction_service.py

This PR refactors retry sending transaction and increase the tests coverage.
- Removed the command functionality from the command layer
- The command business logic is part of `TransactionService` layer which is the component aimed to handle transaction resources. Refactored intended to follow the single responsibility principle and provide loose coupling for testing.
- Added tests to the command logic
- Tests for command handler functionality and for the command business logic inside `TransactionService`.
This PR is related to #270

 Add test to Django command retry_sage_transactions
